/* Generated by Yosys 0.9+3621 (git sha1 84e9fa7, gcc 8.3.1 -fPIC -Os) */

module prng_proj(wb_clk_i, wb_rst_i, wbs_stb_i, wbs_cyc_i, wbs_we_i, wbs_sel_i, wbs_dat_i, wbs_adr_i, wbs_ack_o, wbs_dat_o, la_data_in, la_data_out, la_oen, io_in, io_out, io_oeb);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  input [37:0] io_in;
  output [37:0] io_oeb;
  output [37:0] io_out;
  input [127:0] la_data_in;
  output [127:0] la_data_out;
  input [127:0] la_oen;
  wire \lfsr[100] ;
  wire \lfsr[104] ;
  wire \lfsr[105] ;
  wire \lfsr[106] ;
  wire \lfsr[107] ;
  wire \lfsr[108] ;
  wire \lfsr[109] ;
  wire \lfsr[10] ;
  wire \lfsr[110] ;
  wire \lfsr[111] ;
  wire \lfsr[112] ;
  wire \lfsr[113] ;
  wire \lfsr[114] ;
  wire \lfsr[115] ;
  wire \lfsr[116] ;
  wire \lfsr[117] ;
  wire \lfsr[118] ;
  wire \lfsr[119] ;
  wire \lfsr[11] ;
  wire \lfsr[120] ;
  wire \lfsr[121] ;
  wire \lfsr[122] ;
  wire \lfsr[123] ;
  wire \lfsr[124] ;
  wire \lfsr[125] ;
  wire \lfsr[126] ;
  wire \lfsr[127] ;
  wire \lfsr[128] ;
  wire \lfsr[129] ;
  wire \lfsr[12] ;
  wire \lfsr[130] ;
  wire \lfsr[131] ;
  wire \lfsr[132] ;
  wire \lfsr[136] ;
  wire \lfsr[137] ;
  wire \lfsr[138] ;
  wire \lfsr[139] ;
  wire \lfsr[13] ;
  wire \lfsr[140] ;
  wire \lfsr[141] ;
  wire \lfsr[142] ;
  wire \lfsr[143] ;
  wire \lfsr[144] ;
  wire \lfsr[145] ;
  wire \lfsr[146] ;
  wire \lfsr[147] ;
  wire \lfsr[148] ;
  wire \lfsr[149] ;
  wire \lfsr[14] ;
  wire \lfsr[150] ;
  wire \lfsr[151] ;
  wire \lfsr[152] ;
  wire \lfsr[153] ;
  wire \lfsr[154] ;
  wire \lfsr[155] ;
  wire \lfsr[156] ;
  wire \lfsr[157] ;
  wire \lfsr[158] ;
  wire \lfsr[159] ;
  wire \lfsr[15] ;
  wire \lfsr[160] ;
  wire \lfsr[161] ;
  wire \lfsr[162] ;
  wire \lfsr[163] ;
  wire \lfsr[164] ;
  wire \lfsr[16] ;
  wire \lfsr[17] ;
  wire \lfsr[18] ;
  wire \lfsr[19] ;
  wire \lfsr[20] ;
  wire \lfsr[21] ;
  wire \lfsr[22] ;
  wire \lfsr[23] ;
  wire \lfsr[24] ;
  wire \lfsr[25] ;
  wire \lfsr[26] ;
  wire \lfsr[27] ;
  wire \lfsr[28] ;
  wire \lfsr[29] ;
  wire \lfsr[2] ;
  wire \lfsr[30] ;
  wire \lfsr[31] ;
  wire \lfsr[32] ;
  wire \lfsr[33] ;
  wire \lfsr[34] ;
  wire \lfsr[35] ;
  wire \lfsr[36] ;
  wire \lfsr[37] ;
  wire \lfsr[38] ;
  wire \lfsr[39] ;
  wire \lfsr[3] ;
  wire \lfsr[40] ;
  wire \lfsr[41] ;
  wire \lfsr[42] ;
  wire \lfsr[43] ;
  wire \lfsr[44] ;
  wire \lfsr[45] ;
  wire \lfsr[46] ;
  wire \lfsr[47] ;
  wire \lfsr[48] ;
  wire \lfsr[49] ;
  wire \lfsr[4] ;
  wire \lfsr[50] ;
  wire \lfsr[51] ;
  wire \lfsr[52] ;
  wire \lfsr[53] ;
  wire \lfsr[54] ;
  wire \lfsr[55] ;
  wire \lfsr[56] ;
  wire \lfsr[57] ;
  wire \lfsr[58] ;
  wire \lfsr[59] ;
  wire \lfsr[5] ;
  wire \lfsr[60] ;
  wire \lfsr[61] ;
  wire \lfsr[62] ;
  wire \lfsr[63] ;
  wire \lfsr[64] ;
  wire \lfsr[65] ;
  wire \lfsr[66] ;
  wire \lfsr[67] ;
  wire \lfsr[68] ;
  wire \lfsr[6] ;
  wire \lfsr[72] ;
  wire \lfsr[73] ;
  wire \lfsr[74] ;
  wire \lfsr[75] ;
  wire \lfsr[76] ;
  wire \lfsr[77] ;
  wire \lfsr[78] ;
  wire \lfsr[79] ;
  wire \lfsr[7] ;
  wire \lfsr[80] ;
  wire \lfsr[81] ;
  wire \lfsr[82] ;
  wire \lfsr[83] ;
  wire \lfsr[84] ;
  wire \lfsr[85] ;
  wire \lfsr[86] ;
  wire \lfsr[87] ;
  wire \lfsr[88] ;
  wire \lfsr[89] ;
  wire \lfsr[8] ;
  wire \lfsr[90] ;
  wire \lfsr[91] ;
  wire \lfsr[92] ;
  wire \lfsr[93] ;
  wire \lfsr[94] ;
  wire \lfsr[95] ;
  wire \lfsr[96] ;
  wire \lfsr[97] ;
  wire \lfsr[98] ;
  wire \lfsr[99] ;
  wire \lfsr[9] ;
  input wb_clk_i;
  input wb_rst_i;
  output wbs_ack_o;
  input [31:0] wbs_adr_i;
  input wbs_cyc_i;
  input [31:0] wbs_dat_i;
  output [31:0] wbs_dat_o;
  input [3:0] wbs_sel_i;
  input wbs_stb_i;
  input wbs_we_i;
  wire \xnor_o[0] ;
  sky130_fd_sc_hd__nand2_4 _006_ (
    .A(wbs_stb_i),
    .B(wbs_cyc_i),
    .Y(_004_)
  );
  sky130_fd_sc_hd__or2_4 _007_ (
    .A(wb_rst_i),
    .B(_004_),
    .X(_005_)
  );
  sky130_fd_sc_hd__inv_2 _008_ (
    .A(\xnor_o[0] ),
    .Y(_002_)
  );
  sky130_fd_sc_hd__or2_4 _009_ (
    .A(_002_),
    .B(_005_),
    .X(_003_)
  );
  sky130_fd_sc_hd__a21bo_4 _010_ (
    .A1(io_out[37]),
    .A2(_005_),
    .B1_N(_003_),
    .X(_000_)
  );
  sky130_fd_sc_hd__a21oi_4 _011_ (
    .A1(_002_),
    .A2(_004_),
    .B1(wb_rst_i),
    .Y(_001_)
  );
  sky130_fd_sc_hd__conb_1 _012_ (
    .LO(io_oeb[37])
  );
  sky130_fd_sc_hd__conb_1 _013_ (
    .LO(la_data_out[0])
  );
  sky130_fd_sc_hd__conb_1 _014_ (
    .LO(la_data_out[1])
  );
  sky130_fd_sc_hd__conb_1 _015_ (
    .LO(la_data_out[2])
  );
  sky130_fd_sc_hd__conb_1 _016_ (
    .LO(la_data_out[3])
  );
  sky130_fd_sc_hd__conb_1 _017_ (
    .LO(la_data_out[4])
  );
  sky130_fd_sc_hd__conb_1 _018_ (
    .LO(la_data_out[5])
  );
  sky130_fd_sc_hd__conb_1 _019_ (
    .LO(la_data_out[6])
  );
  sky130_fd_sc_hd__conb_1 _020_ (
    .LO(la_data_out[7])
  );
  sky130_fd_sc_hd__conb_1 _021_ (
    .LO(la_data_out[8])
  );
  sky130_fd_sc_hd__conb_1 _022_ (
    .LO(la_data_out[9])
  );
  sky130_fd_sc_hd__conb_1 _023_ (
    .LO(la_data_out[10])
  );
  sky130_fd_sc_hd__conb_1 _024_ (
    .LO(la_data_out[11])
  );
  sky130_fd_sc_hd__conb_1 _025_ (
    .LO(la_data_out[12])
  );
  sky130_fd_sc_hd__conb_1 _026_ (
    .LO(la_data_out[13])
  );
  sky130_fd_sc_hd__conb_1 _027_ (
    .LO(la_data_out[14])
  );
  sky130_fd_sc_hd__conb_1 _028_ (
    .LO(la_data_out[15])
  );
  sky130_fd_sc_hd__conb_1 _029_ (
    .LO(la_data_out[16])
  );
  sky130_fd_sc_hd__conb_1 _030_ (
    .LO(la_data_out[17])
  );
  sky130_fd_sc_hd__conb_1 _031_ (
    .LO(la_data_out[18])
  );
  sky130_fd_sc_hd__conb_1 _032_ (
    .LO(la_data_out[19])
  );
  sky130_fd_sc_hd__conb_1 _033_ (
    .LO(la_data_out[20])
  );
  sky130_fd_sc_hd__conb_1 _034_ (
    .LO(la_data_out[21])
  );
  sky130_fd_sc_hd__conb_1 _035_ (
    .LO(la_data_out[22])
  );
  sky130_fd_sc_hd__conb_1 _036_ (
    .LO(la_data_out[23])
  );
  sky130_fd_sc_hd__conb_1 _037_ (
    .LO(la_data_out[24])
  );
  sky130_fd_sc_hd__conb_1 _038_ (
    .LO(la_data_out[25])
  );
  sky130_fd_sc_hd__conb_1 _039_ (
    .LO(la_data_out[26])
  );
  sky130_fd_sc_hd__conb_1 _040_ (
    .LO(la_data_out[27])
  );
  sky130_fd_sc_hd__conb_1 _041_ (
    .LO(la_data_out[28])
  );
  sky130_fd_sc_hd__conb_1 _042_ (
    .LO(la_data_out[29])
  );
  sky130_fd_sc_hd__conb_1 _043_ (
    .LO(la_data_out[30])
  );
  sky130_fd_sc_hd__conb_1 _044_ (
    .LO(la_data_out[31])
  );
  sky130_fd_sc_hd__conb_1 _045_ (
    .LO(la_data_out[32])
  );
  sky130_fd_sc_hd__conb_1 _046_ (
    .LO(la_data_out[33])
  );
  sky130_fd_sc_hd__conb_1 _047_ (
    .LO(la_data_out[34])
  );
  sky130_fd_sc_hd__conb_1 _048_ (
    .LO(la_data_out[35])
  );
  sky130_fd_sc_hd__conb_1 _049_ (
    .LO(la_data_out[36])
  );
  sky130_fd_sc_hd__conb_1 _050_ (
    .LO(la_data_out[37])
  );
  sky130_fd_sc_hd__conb_1 _051_ (
    .LO(la_data_out[38])
  );
  sky130_fd_sc_hd__conb_1 _052_ (
    .LO(la_data_out[39])
  );
  sky130_fd_sc_hd__conb_1 _053_ (
    .LO(la_data_out[40])
  );
  sky130_fd_sc_hd__conb_1 _054_ (
    .LO(la_data_out[41])
  );
  sky130_fd_sc_hd__conb_1 _055_ (
    .LO(la_data_out[42])
  );
  sky130_fd_sc_hd__conb_1 _056_ (
    .LO(la_data_out[43])
  );
  sky130_fd_sc_hd__conb_1 _057_ (
    .LO(la_data_out[44])
  );
  sky130_fd_sc_hd__conb_1 _058_ (
    .LO(la_data_out[45])
  );
  sky130_fd_sc_hd__conb_1 _059_ (
    .LO(la_data_out[46])
  );
  sky130_fd_sc_hd__conb_1 _060_ (
    .LO(la_data_out[47])
  );
  sky130_fd_sc_hd__conb_1 _061_ (
    .LO(la_data_out[48])
  );
  sky130_fd_sc_hd__conb_1 _062_ (
    .LO(la_data_out[49])
  );
  sky130_fd_sc_hd__conb_1 _063_ (
    .LO(la_data_out[50])
  );
  sky130_fd_sc_hd__conb_1 _064_ (
    .LO(la_data_out[51])
  );
  sky130_fd_sc_hd__conb_1 _065_ (
    .LO(la_data_out[52])
  );
  sky130_fd_sc_hd__conb_1 _066_ (
    .LO(la_data_out[53])
  );
  sky130_fd_sc_hd__conb_1 _067_ (
    .LO(la_data_out[54])
  );
  sky130_fd_sc_hd__conb_1 _068_ (
    .LO(la_data_out[55])
  );
  sky130_fd_sc_hd__conb_1 _069_ (
    .LO(la_data_out[56])
  );
  sky130_fd_sc_hd__conb_1 _070_ (
    .LO(la_data_out[57])
  );
  sky130_fd_sc_hd__conb_1 _071_ (
    .LO(la_data_out[58])
  );
  sky130_fd_sc_hd__conb_1 _072_ (
    .LO(la_data_out[59])
  );
  sky130_fd_sc_hd__conb_1 _073_ (
    .LO(la_data_out[60])
  );
  sky130_fd_sc_hd__conb_1 _074_ (
    .LO(la_data_out[61])
  );
  sky130_fd_sc_hd__conb_1 _075_ (
    .LO(la_data_out[62])
  );
  sky130_fd_sc_hd__conb_1 _076_ (
    .LO(la_data_out[63])
  );
  sky130_fd_sc_hd__conb_1 _077_ (
    .LO(la_data_out[64])
  );
  sky130_fd_sc_hd__conb_1 _078_ (
    .LO(la_data_out[65])
  );
  sky130_fd_sc_hd__conb_1 _079_ (
    .LO(la_data_out[66])
  );
  sky130_fd_sc_hd__conb_1 _080_ (
    .LO(la_data_out[67])
  );
  sky130_fd_sc_hd__conb_1 _081_ (
    .LO(la_data_out[68])
  );
  sky130_fd_sc_hd__conb_1 _082_ (
    .LO(la_data_out[69])
  );
  sky130_fd_sc_hd__conb_1 _083_ (
    .LO(la_data_out[70])
  );
  sky130_fd_sc_hd__conb_1 _084_ (
    .LO(la_data_out[71])
  );
  sky130_fd_sc_hd__conb_1 _085_ (
    .LO(la_data_out[72])
  );
  sky130_fd_sc_hd__conb_1 _086_ (
    .LO(la_data_out[73])
  );
  sky130_fd_sc_hd__conb_1 _087_ (
    .LO(la_data_out[74])
  );
  sky130_fd_sc_hd__conb_1 _088_ (
    .LO(la_data_out[75])
  );
  sky130_fd_sc_hd__conb_1 _089_ (
    .LO(la_data_out[76])
  );
  sky130_fd_sc_hd__conb_1 _090_ (
    .LO(la_data_out[77])
  );
  sky130_fd_sc_hd__conb_1 _091_ (
    .LO(la_data_out[78])
  );
  sky130_fd_sc_hd__conb_1 _092_ (
    .LO(la_data_out[79])
  );
  sky130_fd_sc_hd__conb_1 _093_ (
    .LO(la_data_out[80])
  );
  sky130_fd_sc_hd__conb_1 _094_ (
    .LO(la_data_out[81])
  );
  sky130_fd_sc_hd__conb_1 _095_ (
    .LO(la_data_out[82])
  );
  sky130_fd_sc_hd__conb_1 _096_ (
    .LO(la_data_out[83])
  );
  sky130_fd_sc_hd__conb_1 _097_ (
    .LO(la_data_out[84])
  );
  sky130_fd_sc_hd__conb_1 _098_ (
    .LO(la_data_out[85])
  );
  sky130_fd_sc_hd__conb_1 _099_ (
    .LO(la_data_out[86])
  );
  sky130_fd_sc_hd__conb_1 _100_ (
    .LO(la_data_out[87])
  );
  sky130_fd_sc_hd__conb_1 _101_ (
    .LO(la_data_out[88])
  );
  sky130_fd_sc_hd__conb_1 _102_ (
    .LO(la_data_out[89])
  );
  sky130_fd_sc_hd__conb_1 _103_ (
    .LO(la_data_out[90])
  );
  sky130_fd_sc_hd__conb_1 _104_ (
    .LO(la_data_out[91])
  );
  sky130_fd_sc_hd__conb_1 _105_ (
    .LO(la_data_out[92])
  );
  sky130_fd_sc_hd__conb_1 _106_ (
    .LO(la_data_out[93])
  );
  sky130_fd_sc_hd__conb_1 _107_ (
    .LO(la_data_out[94])
  );
  sky130_fd_sc_hd__conb_1 _108_ (
    .LO(la_data_out[95])
  );
  sky130_fd_sc_hd__conb_1 _109_ (
    .LO(la_data_out[96])
  );
  sky130_fd_sc_hd__conb_1 _110_ (
    .LO(la_data_out[97])
  );
  sky130_fd_sc_hd__conb_1 _111_ (
    .LO(la_data_out[98])
  );
  sky130_fd_sc_hd__conb_1 _112_ (
    .LO(la_data_out[99])
  );
  sky130_fd_sc_hd__conb_1 _113_ (
    .LO(la_data_out[100])
  );
  sky130_fd_sc_hd__conb_1 _114_ (
    .LO(la_data_out[101])
  );
  sky130_fd_sc_hd__conb_1 _115_ (
    .LO(la_data_out[102])
  );
  sky130_fd_sc_hd__conb_1 _116_ (
    .LO(la_data_out[103])
  );
  sky130_fd_sc_hd__conb_1 _117_ (
    .LO(la_data_out[104])
  );
  sky130_fd_sc_hd__conb_1 _118_ (
    .LO(la_data_out[105])
  );
  sky130_fd_sc_hd__conb_1 _119_ (
    .LO(la_data_out[106])
  );
  sky130_fd_sc_hd__conb_1 _120_ (
    .LO(la_data_out[107])
  );
  sky130_fd_sc_hd__conb_1 _121_ (
    .LO(la_data_out[108])
  );
  sky130_fd_sc_hd__conb_1 _122_ (
    .LO(la_data_out[109])
  );
  sky130_fd_sc_hd__conb_1 _123_ (
    .LO(la_data_out[110])
  );
  sky130_fd_sc_hd__conb_1 _124_ (
    .LO(la_data_out[111])
  );
  sky130_fd_sc_hd__conb_1 _125_ (
    .LO(la_data_out[112])
  );
  sky130_fd_sc_hd__conb_1 _126_ (
    .LO(la_data_out[113])
  );
  sky130_fd_sc_hd__conb_1 _127_ (
    .LO(la_data_out[114])
  );
  sky130_fd_sc_hd__conb_1 _128_ (
    .LO(la_data_out[115])
  );
  sky130_fd_sc_hd__conb_1 _129_ (
    .LO(la_data_out[116])
  );
  sky130_fd_sc_hd__conb_1 _130_ (
    .LO(la_data_out[117])
  );
  sky130_fd_sc_hd__conb_1 _131_ (
    .LO(la_data_out[118])
  );
  sky130_fd_sc_hd__conb_1 _132_ (
    .LO(la_data_out[119])
  );
  sky130_fd_sc_hd__conb_1 _133_ (
    .LO(la_data_out[120])
  );
  sky130_fd_sc_hd__conb_1 _134_ (
    .LO(la_data_out[121])
  );
  sky130_fd_sc_hd__conb_1 _135_ (
    .LO(la_data_out[122])
  );
  sky130_fd_sc_hd__conb_1 _136_ (
    .LO(la_data_out[123])
  );
  sky130_fd_sc_hd__conb_1 _137_ (
    .LO(la_data_out[124])
  );
  sky130_fd_sc_hd__conb_1 _138_ (
    .LO(la_data_out[125])
  );
  sky130_fd_sc_hd__conb_1 _139_ (
    .LO(la_data_out[126])
  );
  sky130_fd_sc_hd__conb_1 _140_ (
    .LO(la_data_out[127])
  );
  sky130_fd_sc_hd__conb_1 _141_ (
    .LO(wbs_ack_o)
  );
  sky130_fd_sc_hd__conb_1 _142_ (
    .LO(wbs_dat_o[0])
  );
  sky130_fd_sc_hd__conb_1 _143_ (
    .LO(wbs_dat_o[1])
  );
  sky130_fd_sc_hd__conb_1 _144_ (
    .LO(wbs_dat_o[2])
  );
  sky130_fd_sc_hd__conb_1 _145_ (
    .LO(wbs_dat_o[3])
  );
  sky130_fd_sc_hd__conb_1 _146_ (
    .LO(wbs_dat_o[4])
  );
  sky130_fd_sc_hd__conb_1 _147_ (
    .LO(wbs_dat_o[5])
  );
  sky130_fd_sc_hd__conb_1 _148_ (
    .LO(wbs_dat_o[6])
  );
  sky130_fd_sc_hd__conb_1 _149_ (
    .LO(wbs_dat_o[7])
  );
  sky130_fd_sc_hd__conb_1 _150_ (
    .LO(wbs_dat_o[8])
  );
  sky130_fd_sc_hd__conb_1 _151_ (
    .LO(wbs_dat_o[9])
  );
  sky130_fd_sc_hd__conb_1 _152_ (
    .LO(wbs_dat_o[10])
  );
  sky130_fd_sc_hd__conb_1 _153_ (
    .LO(wbs_dat_o[11])
  );
  sky130_fd_sc_hd__conb_1 _154_ (
    .LO(wbs_dat_o[12])
  );
  sky130_fd_sc_hd__conb_1 _155_ (
    .LO(wbs_dat_o[13])
  );
  sky130_fd_sc_hd__conb_1 _156_ (
    .LO(wbs_dat_o[14])
  );
  sky130_fd_sc_hd__conb_1 _157_ (
    .LO(wbs_dat_o[15])
  );
  sky130_fd_sc_hd__conb_1 _158_ (
    .LO(wbs_dat_o[16])
  );
  sky130_fd_sc_hd__conb_1 _159_ (
    .LO(wbs_dat_o[17])
  );
  sky130_fd_sc_hd__conb_1 _160_ (
    .LO(wbs_dat_o[18])
  );
  sky130_fd_sc_hd__conb_1 _161_ (
    .LO(wbs_dat_o[19])
  );
  sky130_fd_sc_hd__conb_1 _162_ (
    .LO(wbs_dat_o[20])
  );
  sky130_fd_sc_hd__conb_1 _163_ (
    .LO(wbs_dat_o[21])
  );
  sky130_fd_sc_hd__conb_1 _164_ (
    .LO(wbs_dat_o[22])
  );
  sky130_fd_sc_hd__conb_1 _165_ (
    .LO(wbs_dat_o[23])
  );
  sky130_fd_sc_hd__conb_1 _166_ (
    .LO(wbs_dat_o[24])
  );
  sky130_fd_sc_hd__conb_1 _167_ (
    .LO(wbs_dat_o[25])
  );
  sky130_fd_sc_hd__conb_1 _168_ (
    .LO(wbs_dat_o[26])
  );
  sky130_fd_sc_hd__conb_1 _169_ (
    .LO(wbs_dat_o[27])
  );
  sky130_fd_sc_hd__conb_1 _170_ (
    .LO(wbs_dat_o[28])
  );
  sky130_fd_sc_hd__conb_1 _171_ (
    .LO(wbs_dat_o[29])
  );
  sky130_fd_sc_hd__conb_1 _172_ (
    .LO(wbs_dat_o[30])
  );
  sky130_fd_sc_hd__conb_1 _173_ (
    .LO(wbs_dat_o[31])
  );
  sky130_fd_sc_hd__buf_2 _174_ (
    .A(wb_rst_i),
    .X(io_oeb[0])
  );
  sky130_fd_sc_hd__buf_2 _175_ (
    .A(wb_rst_i),
    .X(io_oeb[1])
  );
  sky130_fd_sc_hd__buf_2 _176_ (
    .A(wb_rst_i),
    .X(io_oeb[2])
  );
  sky130_fd_sc_hd__buf_2 _177_ (
    .A(wb_rst_i),
    .X(io_oeb[3])
  );
  sky130_fd_sc_hd__buf_2 _178_ (
    .A(wb_rst_i),
    .X(io_oeb[4])
  );
  sky130_fd_sc_hd__buf_2 _179_ (
    .A(wb_rst_i),
    .X(io_oeb[5])
  );
  sky130_fd_sc_hd__buf_2 _180_ (
    .A(wb_rst_i),
    .X(io_oeb[6])
  );
  sky130_fd_sc_hd__buf_2 _181_ (
    .A(wb_rst_i),
    .X(io_oeb[7])
  );
  sky130_fd_sc_hd__buf_2 _182_ (
    .A(wb_rst_i),
    .X(io_oeb[8])
  );
  sky130_fd_sc_hd__buf_2 _183_ (
    .A(wb_rst_i),
    .X(io_oeb[9])
  );
  sky130_fd_sc_hd__buf_2 _184_ (
    .A(wb_rst_i),
    .X(io_oeb[10])
  );
  sky130_fd_sc_hd__buf_2 _185_ (
    .A(wb_rst_i),
    .X(io_oeb[11])
  );
  sky130_fd_sc_hd__buf_2 _186_ (
    .A(wb_rst_i),
    .X(io_oeb[12])
  );
  sky130_fd_sc_hd__buf_2 _187_ (
    .A(wb_rst_i),
    .X(io_oeb[13])
  );
  sky130_fd_sc_hd__buf_2 _188_ (
    .A(wb_rst_i),
    .X(io_oeb[14])
  );
  sky130_fd_sc_hd__buf_2 _189_ (
    .A(wb_rst_i),
    .X(io_oeb[15])
  );
  sky130_fd_sc_hd__buf_2 _190_ (
    .A(wb_rst_i),
    .X(io_oeb[16])
  );
  sky130_fd_sc_hd__buf_2 _191_ (
    .A(wb_rst_i),
    .X(io_oeb[17])
  );
  sky130_fd_sc_hd__buf_2 _192_ (
    .A(wb_rst_i),
    .X(io_oeb[18])
  );
  sky130_fd_sc_hd__buf_2 _193_ (
    .A(wb_rst_i),
    .X(io_oeb[19])
  );
  sky130_fd_sc_hd__buf_2 _194_ (
    .A(wb_rst_i),
    .X(io_oeb[20])
  );
  sky130_fd_sc_hd__buf_2 _195_ (
    .A(wb_rst_i),
    .X(io_oeb[21])
  );
  sky130_fd_sc_hd__buf_2 _196_ (
    .A(wb_rst_i),
    .X(io_oeb[22])
  );
  sky130_fd_sc_hd__buf_2 _197_ (
    .A(wb_rst_i),
    .X(io_oeb[23])
  );
  sky130_fd_sc_hd__buf_2 _198_ (
    .A(wb_rst_i),
    .X(io_oeb[24])
  );
  sky130_fd_sc_hd__buf_2 _199_ (
    .A(wb_rst_i),
    .X(io_oeb[25])
  );
  sky130_fd_sc_hd__buf_2 _200_ (
    .A(wb_rst_i),
    .X(io_oeb[26])
  );
  sky130_fd_sc_hd__buf_2 _201_ (
    .A(wb_rst_i),
    .X(io_oeb[27])
  );
  sky130_fd_sc_hd__buf_2 _202_ (
    .A(wb_rst_i),
    .X(io_oeb[28])
  );
  sky130_fd_sc_hd__buf_2 _203_ (
    .A(wb_rst_i),
    .X(io_oeb[29])
  );
  sky130_fd_sc_hd__buf_2 _204_ (
    .A(wb_rst_i),
    .X(io_oeb[30])
  );
  sky130_fd_sc_hd__buf_2 _205_ (
    .A(wb_rst_i),
    .X(io_oeb[31])
  );
  sky130_fd_sc_hd__buf_2 _206_ (
    .A(wb_rst_i),
    .X(io_oeb[32])
  );
  sky130_fd_sc_hd__buf_2 _207_ (
    .A(wb_rst_i),
    .X(io_oeb[33])
  );
  sky130_fd_sc_hd__buf_2 _208_ (
    .A(wb_rst_i),
    .X(io_oeb[34])
  );
  sky130_fd_sc_hd__buf_2 _209_ (
    .A(wb_rst_i),
    .X(io_oeb[35])
  );
  sky130_fd_sc_hd__buf_2 _210_ (
    .A(wb_rst_i),
    .X(io_oeb[36])
  );
  sky130_fd_sc_hd__buf_2 _211_ (
    .A(io_out[37]),
    .X(io_out[0])
  );
  sky130_fd_sc_hd__buf_2 _212_ (
    .A(io_out[37]),
    .X(io_out[1])
  );
  sky130_fd_sc_hd__buf_2 _213_ (
    .A(io_out[37]),
    .X(io_out[2])
  );
  sky130_fd_sc_hd__buf_2 _214_ (
    .A(io_out[37]),
    .X(io_out[3])
  );
  sky130_fd_sc_hd__buf_2 _215_ (
    .A(io_out[37]),
    .X(io_out[4])
  );
  sky130_fd_sc_hd__buf_2 _216_ (
    .A(io_out[37]),
    .X(io_out[5])
  );
  sky130_fd_sc_hd__buf_2 _217_ (
    .A(io_out[37]),
    .X(io_out[6])
  );
  sky130_fd_sc_hd__buf_2 _218_ (
    .A(io_out[37]),
    .X(io_out[7])
  );
  sky130_fd_sc_hd__buf_2 _219_ (
    .A(io_out[37]),
    .X(io_out[8])
  );
  sky130_fd_sc_hd__buf_2 _220_ (
    .A(io_out[37]),
    .X(io_out[9])
  );
  sky130_fd_sc_hd__buf_2 _221_ (
    .A(io_out[37]),
    .X(io_out[10])
  );
  sky130_fd_sc_hd__buf_2 _222_ (
    .A(io_out[37]),
    .X(io_out[11])
  );
  sky130_fd_sc_hd__buf_2 _223_ (
    .A(io_out[37]),
    .X(io_out[12])
  );
  sky130_fd_sc_hd__buf_2 _224_ (
    .A(io_out[37]),
    .X(io_out[13])
  );
  sky130_fd_sc_hd__buf_2 _225_ (
    .A(io_out[37]),
    .X(io_out[14])
  );
  sky130_fd_sc_hd__buf_2 _226_ (
    .A(io_out[37]),
    .X(io_out[15])
  );
  sky130_fd_sc_hd__buf_2 _227_ (
    .A(io_out[37]),
    .X(io_out[16])
  );
  sky130_fd_sc_hd__buf_2 _228_ (
    .A(io_out[37]),
    .X(io_out[17])
  );
  sky130_fd_sc_hd__buf_2 _229_ (
    .A(io_out[37]),
    .X(io_out[18])
  );
  sky130_fd_sc_hd__buf_2 _230_ (
    .A(io_out[37]),
    .X(io_out[19])
  );
  sky130_fd_sc_hd__buf_2 _231_ (
    .A(io_out[37]),
    .X(io_out[20])
  );
  sky130_fd_sc_hd__buf_2 _232_ (
    .A(io_out[37]),
    .X(io_out[21])
  );
  sky130_fd_sc_hd__buf_2 _233_ (
    .A(io_out[37]),
    .X(io_out[22])
  );
  sky130_fd_sc_hd__buf_2 _234_ (
    .A(io_out[37]),
    .X(io_out[23])
  );
  sky130_fd_sc_hd__buf_2 _235_ (
    .A(io_out[37]),
    .X(io_out[24])
  );
  sky130_fd_sc_hd__buf_2 _236_ (
    .A(io_out[37]),
    .X(io_out[25])
  );
  sky130_fd_sc_hd__buf_2 _237_ (
    .A(io_out[37]),
    .X(io_out[26])
  );
  sky130_fd_sc_hd__buf_2 _238_ (
    .A(io_out[37]),
    .X(io_out[27])
  );
  sky130_fd_sc_hd__buf_2 _239_ (
    .A(io_out[37]),
    .X(io_out[28])
  );
  sky130_fd_sc_hd__buf_2 _240_ (
    .A(io_out[37]),
    .X(io_out[29])
  );
  sky130_fd_sc_hd__buf_2 _241_ (
    .A(io_out[37]),
    .X(io_out[30])
  );
  sky130_fd_sc_hd__buf_2 _242_ (
    .A(io_out[37]),
    .X(io_out[31])
  );
  sky130_fd_sc_hd__buf_2 _243_ (
    .A(io_out[37]),
    .X(io_out[32])
  );
  sky130_fd_sc_hd__buf_2 _244_ (
    .A(io_out[37]),
    .X(io_out[33])
  );
  sky130_fd_sc_hd__buf_2 _245_ (
    .A(io_out[37]),
    .X(io_out[34])
  );
  sky130_fd_sc_hd__buf_2 _246_ (
    .A(io_out[37]),
    .X(io_out[35])
  );
  sky130_fd_sc_hd__buf_2 _247_ (
    .A(io_out[37]),
    .X(io_out[36])
  );
  sky130_fd_sc_hd__dfxtp_4 _248_ (
    .CLK(wb_clk_i),
    .D(_000_),
    .Q(io_out[37])
  );
  sky130_fd_sc_hd__dfxtp_4 _249_ (
    .CLK(wb_clk_i),
    .D(_001_),
    .Q(\xnor_o[0] )
  );
endmodule
